"""empty message

Revision ID: bbbf8633dd94
Revises: cd2cd4332cc2
Create Date: 2022-11-25 03:15:53.633885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbbf8633dd94'
down_revision = 'cd2cd4332cc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('create_at')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('create_at')

    # ### end Alembic commands ###
